# .devcontainer/docker-compose.yml
version: '3.8'

services:
  php-apache:
    # Build from Dockerfile in the parent folder context
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    # Map container’s port 80 to localhost:8080
    ports:
      - "8080:80"

    # Tells Docker to spin up MySQL first
    depends_on:
      - mysql

    # Mount the whole repo in /workspace
    volumes:
      - ..:/workspace:cached

    # Use the 'vscode' user created in the Dockerfile
    user: "vscode"

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
