version: '3.8'

services:
  apache-php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ../..:/workspaces
    # If you already set CMD in the Dockerfile, remove command:
    # command: apache2ctl -D FOREGROUND

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=devuser
      - PMA_PASSWORD=devpass
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql-data:
