version: '3.8'

services:
  apache-php:
    build: .
    # Map container port 80 to local port 8080
    ports:
      - "8080:80"
    volumes:
      # Mount your repo into /var/www/html so you can edit PHP files live
      - .:/var/www/html

  mysql:
    image: mysql:8.0
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
