# .devcontainer/docker-compose.yml
version: '3.8'

services:
  apache-php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ..:/var/www/html
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
    networks:
      - dev-network

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=devuser
      - PMA_PASSWORD=devpass
    depends_on:
      - mysql
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  mysql_data: